### ISSUE TITLE
Stats/Credits not working unless bots

### ISSUE THREAD

**Issue by johandrevwyk** [Kxnrl/MiniGames#18]
I recently added minigames onto my server, I did the setup and everything correctly, I have the latest version of everything.

When you kill someone in game, its supposed to give you credits, if im not mistaken.

After removing bots from my server, I noticed that it completely disappears, and stats do not even get affected.

I have tried
- bot_quota
- bot_kick
- -nobots on startup

a bot_quota above 7 seems to make the stats work, but you cant go lower than that. I have tried a fresh install about 5 times now

**Comment by Kxnrl** [comment]
check you minigames.cfg

**Comment by johandrevwyk** [comment]
I had to end up digging to see what is doing it, the wording you used for the cvar makes it extremely hard to understand, "bonus" means something extra. People won't ever know this cvar is meant for the minimum amount of players for ANYTHING to count

`// How many player requires to enable bouns  
// -  
// Default: "8"  
// Minimum: "1.000000"  
// Maximum: "64.000000"  
mg_bonus_requires_players "1"`

**Comment by Kxnrl** [comment]
sorry, my native language is NOT English.
but int any case, You should check plugins configs before starting server.

**Comment by johandrevwyk** [comment]
i checked every single config in the server, i reinstalled 5 times, thats why i said, its very badly worded, no one would ever have figured it out, im surprised not more people are commenting on it, but in any case, i will reword it for you

`// How many players required to enable stats and credit earning`
